version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: DBIntegracionContinua
    environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=Awsd$34051001.
        - MSSQL_USER=jferber18
        - MSSQL_Pass=Awsd$34051001.
        - MSSQL_PID=Developer 
    ports:
      - "1433:1433"
    networks:
      - app-network

  integracioncontinua:
    image: ${DOCKER_REGISTRY-}integracioncontinua
    build:
      context: .
      dockerfile: IntegracionContinua/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=Server=localhost,1433;Database=Integracion;User Id=jferber18;Password=Awsd$34051001.;
    ports:
      - "8080:80"
    depends_on:
      - "sqlserver"
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge